### ISSUE TITLE
FE3 parched firmware for non AMD flash?

### ISSUE THREAD

**Issue by repetto74** [ops/FE3-Firmware#1]
Hi,
i am building an Fe3 board but I am using an SST 512k flash which will trigger a “vendor error” when loading the Fe3 firmware. 
Is there any patched firmware which will unlock the firmware and allow to program it also with non AMD flash chip?

Many thanks 
Riccardo

**Comment by ops** [comment]
Send me an email to address you can find from my GitHub page. I'll send flasher back.

**Comment by ops** [comment]
Closed via #2
